/usr/bin/x86_64-w64-mingw32-cmake -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-x86_64-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release -DSMTG_PLUGIN_TARGET_USER_PATH=/mnt/c/Program\ Files/Common\ Files/VST3 -DSMTG_ADD_VSTGUI=OFF -DVSTGUI_STANDALONE=OFF -DSMTG_RUN_VST_VALIDATOR=OFF -DSMTG_ADD_VST3_HOSTING_SAMPLES=OFF -DSMTG_CREATE_PLUGIN_LINK=OFF ..

#-DVST3_SDK_DIR=../vst3sdk 
